name: Detox Integration Tests - Android

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # Sharp CLI enables faster image generation during prebuild
      # https://github.com/expo/expo-cli/issues/2676
      - name: Install Sharp CLI for faster image generation during prebuild
        run: yarn global add sharp-cli

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Prepare files for gradlew command
        run: expo prebuild --platform android

      - name: Install Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build Android app locally with gradlew
        run: yarn detox build --configuration android

      - run: ls -al android/
      - run: ls -al android/app/
      - run: ls -al android/app/build/
      - run: ls -al android/app/build/outputs/
      - run: ls -al android/app/build/outputs/apk/
      - run: ls -al android/app/build/outputs/apk/release/
      - run: ls -al android/app/build/outputs/apk/androidTest/
      - run: ls -al android/app/build/outputs/apk/androidTest/release/
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_3a_API_30
          script: yarn detox test --configuration android
