name: Detox Integration Tests - iOS

on: [push]

jobs:
  build:
    name: Detox Integration Tests - iOS
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.8.15

      # Sharp CLI enables faster image generation during prebuild
      # https://github.com/expo/expo-cli/issues/2676
      - name: Install Sharp CLI for faster image generation during prebuild
        run: yarn global add sharp-cli

      - name: Prepare files for xcodebuild command
        run: yarn expo prebuild --platform ios

      - name: Build iOS app locally with xcodebuild
        run: yarn detox build --configuration ios

      - name: Set up Simulator for Detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run tests
        run: yarn detox test --configuration ios

      # Store any Detox screenshots on test failure
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: .detoxArtifacts
