name: Detox Integration Tests - iOS

on: [push]

jobs:
  build:
    name: Detox Integration Tests - iOS

    # macos-13 fails with a Detox error about the iPhone 13 Pro device type:
    # ```
    # DetoxRuntimeError: Failed to find a device by type = "iPhone 13 Pro"
    # HINT: Run 'applesimutils --list' to list your supported devices. It is advised only to specify a device type, e.g., "iPhone XÊ€" and avoid explicit search by OS version.
    # ```
    # However, applesimutils --list reports that a device with "iPhone 13 Pro" exists
    runs-on: macos-12

    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Sharp CLI enables faster image generation during prebuild
      # https://github.com/expo/expo-cli/issues/2676
      - name: Install Sharp CLI for faster image generation during prebuild
        run: npm install --global sharp-cli

      - name: Prepare files for xcodebuild command
        run: pnpm expo prebuild --platform ios

      - name: Switch to CommonJS for Detox config
        run: |
          # Switch "type": "module" to "type": "commonjs" in package.json
          sed -i'' -e $'s/"type": "module"/"type": "commonjs"/g' package.json

      - name: Build iOS app locally with xcodebuild
        run: pnpm detox build --configuration ios

      - name: Set up Simulator for Detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run tests
        run: pnpm detox test --configuration ios

      # Store any Detox screenshots on test failure
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: .detoxArtifacts
