name: Detox Integration Tests - Android

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # Sharp CLI enables faster image generation during prebuild
      # https://github.com/expo/expo-cli/issues/2676
      - name: Install Sharp CLI for faster image generation during prebuild
        run: yarn global add sharp-cli

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Prepare files for gradlew command
        run: expo prebuild --platform android

      # Bug in Gradle 6.9 causing following error:
      #
      # com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
      # > Task :app:mergeExtDexRelease FAILED
      # Type androidx.appcompat.app.ActionBar$DisplayOptions is defined multiple times
      #
      # https://github.com/gradle/gradle/issues/15536
      # https://github.com/gradle/gradle/issues/19372
      #
      # Apparently Gradle has been updated to 7.3.3
      # since Expo is supporting React Native 0.68
      #
      # https://github.com/expo/expo/commit/d566f199bdb03f738c8a785283e847b6a00ec37a
      - run: sed -i'' -e 's/gradle-6.9-all.zip/gradle-6.9.2-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties

      - name: Install Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build Android app locally with gradlew
        run: yarn detox build --configuration android

      - name: Cache AVD snapshot
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30-aosp-atd

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: aosp_atd
          api-level: 30
          arch: x86
          channel: canary
          profile: pixel
          avd-name: Pixel_3a_API_30_AOSP
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching"

      - name: Start emulator and run Detox integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: aosp_atd
          api-level: 30
          arch: x86
          channel: canary
          profile: pixel
          avd-name: Pixel_3a_API_30_AOSP
          script: yarn detox test --configuration android

      - name: Store Detox artifacts on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: .detoxArtifacts
