name: Lint, Check Types, Jest
on: push

jobs:
  build:
    name: Lint, Check Types, Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn --frozen-lockfile
      - run: yarn eslint . --max-warnings 0
      - run: yarn tsc
