name: Lint, Check Types, Jest
on: push

jobs:
  build:
    name: Lint, Check Types, Jest
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - run: pnpm eslint . --max-warnings 0

      - run: pnpm tsc
