name: Temporary test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install newer Bash and coreutils (for timeout)
        run: |
          brew install bash coreutils
      - run: |
          { timeout 120 sleep 1 && echo 1st && sleep 20 && echo 'long end'; } &
          { timeout 120 sleep 3 && echo second && exit 1; } &
          wait -n
          exit_code=$?
          pkill -P $$
          exit $exit_code
          
